# Create a first temporary image named "builder"
FROM golang:1.19.1 AS builder
# Copy Go code (in "builder")
WORKDIR /src/
COPY . .
# Build executables (in "builder")
RUN go build -o /app/webapi ./cmd/webapi




# Create final container
FROM debian:bookworm
# Inform Docker about which port is used
EXPOSE 3000
# Copy the executable from the "builder" image
WORKDIR /app/
COPY --from=builder /app/webapi ./
# Set the default program to our Go backend
CMD ["/app/webapi"]